version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: always

volumes:
  my_dbdata:
